### ISSUE TITLE
Webinterface

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/oerp-tools#2]
Hallo,

Ich hab mal ein mini [Webinterface](https://github.com/fau-fablab/oerp-tools/blob/master/index.php) gebaut, das man evtl. auf der `ws01` hosten könnte, damit $Windows User schmerzbefreit [nextprodid](https://github.com/fau-fablab/oerp-tools/blob/master/nextprodid.py) und so verwenden können.

Allerdings muss man dann in die config einen `user` und ein `passwort` eintragen. Kann man da vielleicht einen `readonly` user anlegen, damit niemand, wenn das passwort irgendwie raus kommt, böse dinge anstellen kann?

**Comment by mgmax** [comment]
readonly user gibts leider ned. etiketten hat auch einen user, den kann 
man genauso dafür verwenden. siehe ws01.

**Comment by sedrubal** [comment]
ok cool

**Comment by sedrubal** [comment]
Durch 6fa55165a3c671b08f389e8773eabf6013c7bd3c und 7eecfd3928e64bd89395ca1a32cc21633c01fecb und durch die Dateiberechtigungen sollte es nun sicher genug sein.

Das Webinterface ist nun auf hier erreichbar: http://ws01/oerp-tools/public/
